name: Build LaTeX PDF

on:
  push:
    paths:
      - ".github/workflows/archaios.yml"
      - "src/**"
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PDF (latexmk)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: src
          latexmk_shell_escape: false
          # без extra_fonts, без latexmk_use_biber
          pre_compile: echo "Start LaTeX build"
          post_compile: echo "LaTeX build done"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: src/main.pdf
