name: build_latex
on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/latex.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live (minimal + needed pkgs)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-base texlive-latex-base texlive-latex-recommended \
            texlive-latex-extra texlive-fonts-recommended \
            texlive-binaries texlive-science texlive-bibtex-extra \
            latexmk ghostscript

      - name: Build (pdflatex → bibtex → pdflatex ×2)
        working-directory: src
        run: |
          pdflatex -interaction=nonstopmode -file-line-error main.tex
          bibtex main
          pdflatex -interaction=nonstopmode -file-line-error main.tex
          pdflatex -interaction=nonstopmode -file-line-error main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: localized-trace-formula-pdf
          path: src/main.pdf
          if-no-files-found: error
          retention-days: 14
          overwrite: true
