name: build_latex
on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/latex.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Надёжно: полный TeX Live + latexmk
      - name: Install TeX Live (full)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends texlive-full latexmk

      # Сборка одной командой; latexmk сам сделает bibtex и нужные прогоны
      - name: Build PDF with latexmk (BibTeX-aware)
        working-directory: src
        run: |
          latexmk -pdf -bibtex -interaction=nonstopmode -file-line-error main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: localized-trace-formula-pdf
          path: src/main.pdf
          if-no-files-found: error
          retention-days: 14
          overwrite: true
