name: Build LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended latexmk

      - name: Build PDF
        run: |
          cd src
          latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: src/main.pdf
