name: latex

on:
  push:
  pull_request:

jobs:
  pdf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Минимальная проверка структуры (чтобы падать раньше и понятнее)
      - name: Sanity check layout
        run: |
          test -f main.tex || { echo "::error ::src/main.tex not found"; exit 2; }
          test -f bib/references.bib || { echo "::error ::src/bib/references.bib not found"; exit 2; }
          for f in macros/environments.tex macros/operators.tex macros/house-style.tex ; do
            test -f "$f" || { echo "::error ::missing $f"; exit 2; }
          done

      - name: Compile with TeX Live (latexmk + BibTeX)
        uses: xu-cheng/latex-action@v3
        with:
          # Ключевой момент: фиксируем год TeX Live, чтобы не было cross-release обновлений
          texlive_version: 2024
          root_file: main.tex
          working_directory: src
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          latexmk_use_lualatex: false
          latexmk_use_xelatex: false

          # Выполняется ПОСЛЕ установки TeX Live, ДО сборки.
          # Никаких self-update! Выбираем зеркало и ставим только нужные пакеты.
          pre_compile: |
            set -e
            mirrors=(
              https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/tlnet-final
              https://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet
              https://mirrors.rit.edu/CTAN/systems/texlive/tlnet
              https://mirror.ctan.org/systems/texlive/tlnet
            )
            for m in "${mirrors[@]}"; do
              if tlmgr option repository "$m" && tlmgr update --list >/dev/null 2>&1; then
                echo "Using TeX Live repo: $m"
                break
              fi
            done
            # Устанавливаем только то, что реально используется в main.tex
            tlmgr install \
              amsmath amsfonts amssymb mathtools bm bbm mathrsfs \
              microtype hyperref cleveref enumitem xcolor \
              graphicx caption subcaption float \
              tcolorbox lmodern url xurl \
              bibtex latexmk

          post_compile: |
            ls -lah || true
            # сохраняем лог рядом со src, чтобы шаг артефакта всегда его нашёл
            cp main.log "$GITHUB_WORKSPACE/src/main.log" 2>/dev/null || true

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: monograph-pdf
          path: src/main.pdf

      - name: Upload LaTeX log (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: main-log
          path: src/main.log
