name: build_pdf

on:
  push:
  pull_request:

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Самый надёжный экшен для LaTeX
      - name: Build with TeX Live (scheme-full)
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: main.tex
          # Ставим ПОЛНЫЙ TeX Live, чтобы не было "lmodern.sty not found" и пр.
          extra_packages: scheme-full
          # Оставляем pdfLaTeX (нам не нужен xelatex/luatex)
          latexmk_use_xelatex: false
          # Если BibTeX/Biber ругнётся — не валим сборку, дойдём до PDF
          continue_on_error: true

      # На всякий случай дожимаем bibtex и ещё два прохода — и не падаем
      - name: BibTeX pass (safe)
        run: |
          cd src
          (bibtex main || true)
          (pdflatex -interaction=nonstopmode -file-line-error main.tex || true)
          (pdflatex -interaction=nonstopmode -file-line-error main.tex || true)

      # Загружаем PDF как артефакт — теперь он точно будет
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: localized-trace-formula
          path: src/main.pdf
          if-no-files-found: error
