name: pdf

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  pdf:
    runs-on: ubuntu-latest

    # Только рабочая папка; shell без флагов!
    defaults:
      run:
        working-directory: src
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check layout
        run: |
          set -euo pipefail
          echo "PWD=$(pwd)"
          ls -la
          test -f main.tex || { echo "::error ::src/main.tex not found"; exit 2; }
          test -f bib/references.bib || { echo "::error ::src/bib/references.bib not found"; exit 2; }
          test -f macros/environments.tex || { echo "::error ::macros/environments.tex missing"; exit 2; }
          test -f macros/operators.tex    || { echo "::error ::macros/operators.tex missing"; exit 2; }
          test -f macros/house-style.tex  || { echo "::error ::macros/house-style.tex missing"; exit 2; }

      - name: Compile with TeXLive (latexmk+BibTeX)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: src
          # latexmk опции: показывать строку ошибки и останавливаться на ней
          extra_latexmk_options: "-file-line-error -halt-on-error -interaction=nonstopmode"
          # Скопируем лог наружу для артефактов
          post_compile: |
            set -euo pipefail
            echo "— build tree —"
            ls -lah
            cp main.log "$GITHUB_WORKSPACE/main.log" || true

      # Загрузить PDF (если собрался)
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: monograph-pdf
          path: src/main.pdf
          if-no-files-found: ignore

      # Лог на случай падения сборки
      - name: Upload LaTeX log (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: main-log
          path: main.log
          if-no-files-found: ignore
