name: latex

on:
  push:
  pull_request:

jobs:
  pdf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - name: Sanity check layout
        run: |
          set -e
          test -f main.tex || { echo "::error ::src/main.tex not found"; exit 2; }
          test -f bib/references.bib || { echo "::error ::src/bib/references.bib not found"; exit 2; }
          for f in macros/environments.tex macros/operators.tex macros/house-style.tex ; do
            test -f "$f" || { echo "::error ::missing $f"; exit 2; }
          done

      # Полный TeX Live внутри контейнера экшена. Ничего качать не нужно.
      - name: Build PDF (full TeX Live)
        uses: dante-ev/latex-action@v2
        with:
          root_file: main.tex
          working_directory: src
          args: -pdf -interaction=nonstopmode -halt-on-error -file-line-error

      - name: Upload PDF
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: monograph-pdf
          path: src/main.pdf

      - name: Upload LaTeX log (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: main-log
          path: src/main.log
