name: build_pdf

on:
  push:
  pull_request:

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ставим полную TeX Live
      - name: Install TeX Live full
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      # Собираем PDF (сначала pdflatex, потом bibtex, потом дважды pdflatex)
      - name: Build PDF
        working-directory: src
        run: |
          pdflatex -interaction=nonstopmode -file-line-error main.tex || true
          bibtex main || true
          pdflatex -interaction=nonstopmode -file-line-error main.tex || true
          pdflatex -interaction=nonstopmode -file-line-error main.tex || true

      # Загружаем PDF как артефакт
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: localized-trace-formula
          path: src/main.pdf
          if-no-files-found: error
