name: Build LaTeX PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install TeX Live
        run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk
      - name: Build PDF
        run: latexmk -pdf -output-directory=build src/main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: paper
          path: build/main.pdf
