name: LaTeX build (arXiv/Annals)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pdf tools (logs sanity)
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript poppler-utils

      # --- pass 1: pdflatex (arXiv-совместимый) ---
      - name: Compile with pdflatex (latex-action)
        id: pdflatex
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: main.tex
          latexmk_use_xelatex: false
          latexmk_use_lualatex: false
          latexmk_shell_escape: false
          args: -pdf -interaction=nonstopmode -halt-on-error -file-line-error
          # после сборки скопируем логи в dist (даже если не собралось на 100%)
          post_compile: |
            mkdir -p dist/logs
            cp -f main.log   dist/logs/  || true
            cp -f main.blg   dist/logs/  || true
            cp -f main.bbl   dist/logs/  || true
            cp -f main.bcf   dist/logs/  || true
            cp -f main.run.xml dist/logs/ || true
            cp -f main.pdf   dist/       || true

      # --- fallback: xelatex (если вдруг шрифты/Unicode) ---
      - name: Compile with xelatex (fallback)
        if: ${{ !exists('src/main.pdf') }}
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: false
          args: -interaction=nonstopmode -halt-on-error -file-line-error
          post_compile: |
            mkdir -p dist/logs
            cp -f main.log   dist/logs/  || true
            cp -f main.blg   dist/logs/  || true
            cp -f main.bbl   dist/logs/  || true
            cp -f main.pdf   dist/       || true

      # --- верификация и печать заголовка PDF ---
      - name: Verify PDF and print info
        run: |
          test -s src/main.pdf
          echo "==================== PDFINFO ===================="
          pdfinfo src/main.pdf || true
          echo "================================================="
          mkdir -p dist
          cp -f src/main.pdf dist/localized-trace-formula.pdf

      # --- артефакты (всегда) ---
      - name: Upload PDF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: localized-trace-formula-pdf
          path: dist/localized-trace-formula.pdf
          if-no-files-found: warn
          retention-days: 14

      - name: Upload LaTeX logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: latex-logs
          path: |
            src/dist/logs/**
            dist/logs/**
            src/main.log
            src/main.blg
            src/main.bbl
          retention-days: 14
