name: build_latex

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live (full set for fonts + bibtex/biber/tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-bibtex-extra \
            biber \
            latexmk \
            lmodern \
            ghostscript

      - name: Build PDF with latexmk
        working-directory: src
        run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error main.tex
          # bibtex/biber при необходимости подтянутся автоматически
          latexmk -pdf main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: src/main.pdf
