name: LaTeX build (arXiv/Annals)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile monograph (pdf)
        id: compile
        uses: xu-cheng/latex-action@v3
        with:
          texlive_version: 2024
          working_directory: src
          root_file: main.tex
          compiler: latexmk
          args: -pdf -file-line-error -interaction=nonstopmode -halt-on-error
          latexmk_use_lualatex: false
          latexmk_use_xelatex: false

      - name: Upload PDF artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: monograph-pdf
          path: src/main.pdf

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monograph-logs
          path: |
            src/*.log
            src/*.blg
            src/*.bbl
            src/*.aux
            src/*.fls
            src/*.fdb_latexmk
