name: LaTeX build (arXiv/Annals)

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Compile monograph (pdf)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- linters & pdf utils ---
      - name: Install chktex + pdf tools
        run: |
          sudo apt-get update
          sudo apt-get install -y chktex ghostscript poppler-utils

      - name: Lint TeX with chktex
        working-directory: src
        run: |
          find . -name "*.tex" -print0 | xargs -0 -n1 -I{} bash -c \
          'echo "::group::chktex {}"; chktex -q -n1 -n8 -n46 {}; echo "::endgroup::"'

      # --- compile with latex-action ---
      - name: Compile (pdflatex + bibtex via latexmk)
        uses: xu-cheng/latex-action@v3
        with:
          # работаем прямо в каталоге src
          working_directory: src
          root_file: main.tex
          # по умолчанию latexmk дергает bibtex — это нам и нужно
          latexmk_use_xelatex: false
          latexmk_use_lualatex: false
          latexmk_shell_escape: false
          # строгий режим latexmk
          args: -pdf -interaction=nonstopmode -halt-on-error -file-line-error

      # --- sanity checks for produced PDF ---
      - name: Verify PDF
        run: |
          test -s src/main.pdf
          pdfinfo src/main.pdf
          gs -o /dev/null -sDEVICE=nullpage -dBATCH -dNOPAUSE src/main.pdf

      # --- upload artifact ---
      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp src/main.pdf dist/localized-trace-formula.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: localized-trace-formula-pdf
          path: dist/localized-trace-formula.pdf
          if-no-files-found: error
          retention-days: 14

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Attach PDF to GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: localized-trace-formula-pdf
          path: dist

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/localized-trace-formula.pdf
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
