name: pdf

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pdf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check layout
        run: |
          test -f main.tex || { echo "::error ::src/main.tex not found"; exit 2; }
          test -f bib/references.bib || { echo "::error ::src/bib/references.bib not found"; exit 2; }
          for f in macros/environments.tex macros/operators.tex macros/house-style.tex; do
            test -f "$f" || { echo "::error ::missing $f"; exit 2; }
          done
          BAD=$(grep -R -nE '\\input\{(sub/|/|\\\.\.)' . || true)
          if [ -n "$BAD" ]; then
            echo "::error ::Forbidden \\input path(s) detected:"; echo "$BAD"; exit 3
          fi

      - name: Compile with TeX Live (latexmk + BibTeX)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: src
          latexmk_use_xelatex: true
          pre_compile: |
            tlmgr option repository https://mirror.ctan.org/systems/texlive/tlnet || true
            tlmgr update --self --all || true
            tlmgr install \
              bbm mathrsfs microtype enumitem float caption subcaption \
              tcolorbox cleveref xcolor etoolbox || true
            echo "[tlmgr pre_compile finished]"
          args: -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Upload PDF
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: monograph-pdf
          path: src/main.pdf

      - name: Upload LaTeX log (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: main-log
          path: src/main.log
