name: build_latex

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live + tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-bibtex-extra \
            biber \
            latexmk \
            lmodern \
            ghostscript

      # Если ты используешь классическую схему BibTeX (\bibliographystyle + \bibliography)
      - name: Build PDF with latexmk (BibTeX-aware)
        working-directory: src
        run: |
          # 1-й прогон (с принудительным продолжением даже при ошибках)
          latexmk -pdf -bibtex -f -interaction=nonstopmode -halt-on-error -file-line-error main.tex
          # 2-й прогон, чтобы устаканить ссылки/кросс-рефы
          latexmk -pdf -bibtex -f main.tex

      # --- Альтернатива: если перейдёшь на biblatex/biber, поменяй верхний шаг на этот:
      # - name: Build PDF with latexmk (Biber-aware)
      #   working-directory: src
      #   run: |
      #     latexmk -pdf -pdflatex="pdflatex %O %S" -use-biber -f -interaction=nonstopmode -halt-on-error -file-line-error main.tex
      #     latexmk -pdf -use-biber -f main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: src/main.pdf
